### ISSUE TITLE
Create purchase page

### ISSUE THREAD

**Issue by Dcamo001** [Dcamo001/dcamo001.github.io#11]
http://www.furstyprints.com/

**Comment by awitherow** [comment]
Looking at some simple integrations, and something that won't burn a hole in your earnings... this looks kind of promising on a quick search: https://github.com/paylike/webshop-example

**Comment by Dcamo001** [comment]
That looks good. Got my site deployed to heroku (camozzo-photography.herokuapp.com) but I don't have it hosted there

**Comment by Dcamo001** [comment]
Complete with this commit: https://github.com/Dcamo001/dcamo001.github.io/commit/c3cde6367469f212986b5ebac45343cfeb304ba6
